name: Publish OCI
on:
  push:
    tags:
      - 'v*'

jobs:
  publish-oci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: build-image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: nomad-holepunch
          tags: ${{ github.ref_name }}
          containerfiles: |
            ./Containerfile

      - name: login-ghcr
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io/shoenig
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: publish-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/shoenig

